INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (1, 1, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (2, 1, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (3, 1, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (4, 1, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (5, 1, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (6, 2, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (7, 2, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (8, 2, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (9, 2, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (10, 2, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (11, 3, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (12, 3, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (13, 3, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (14, 3, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (15, 3, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (16, 4, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (17, 4, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (18, 4, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (19, 4, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (20, 4, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (21, 5, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (22, 5, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (23, 5, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (24, 5, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (25, 5, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (26, 6, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (27, 6, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (28, 6, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (29, 6, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (30, 6, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (31, 7, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (32, 7, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (33, 7, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (34, 7, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (35, 7, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (36, 8, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (37, 8, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (38, 8, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (39, 8, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (40, 8, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (41, 9, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (42, 9, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (43, 9, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (44, 9, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (45, 9, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (46, 9, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (47, 9, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (48, 9, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (49, 9, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (50, 9, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (51, 11, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (52, 11, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (53, 11, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (54, 11, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (55, 11, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (56, 12, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (57, 12, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (58, 12, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (59, 12, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (60, 12, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (61, 13, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (62, 13, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (63, 13, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (64, 13, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (65, 13, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (66, 14, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (67, 14, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (68, 14, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (69, 14, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (70, 14, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (71, 15, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (72, 15, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (73, 15, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (74, 15, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (75, 15, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (76, 16, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (77, 16, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (78, 16, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (79, 16, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (80, 16, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (81, 17, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (82, 17, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (83, 17, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (84, 17, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (85, 17, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (86, 18, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (87, 18, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (88, 18, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (89, 18, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (90, 18, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (91, 19, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (92, 19, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (93, 19, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (94, 19, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (95, 19, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (96, 19, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (97, 19, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (98, 19, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (99, 19, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (100, 19, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (101, 21, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (102, 21, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (103, 21, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (104, 21, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (105, 21, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (106, 22, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (107, 22, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (108, 22, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (109, 22, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (110, 22, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (111, 23, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (112, 23, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (113, 23, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (114, 23, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (115, 23, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (116, 24, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (117, 24, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (118, 24, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (119, 24, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (120, 24, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (121, 25, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (122, 25, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (123, 25, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (124, 25, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (125, 25, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (126, 26, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (127, 26, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (128, 26, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (129, 26, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (130, 26, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (131, 27, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (132, 27, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (133, 27, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (134, 27, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (135, 27, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (136, 28, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (137, 28, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (138, 28, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (139, 28, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (140, 28, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (141, 29, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (142, 29, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (143, 29, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (144, 29, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (145, 29, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (146, 29, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (147, 29, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (148, 29, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (149, 29, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (150, 29, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (151, 31, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (152, 31, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (153, 31, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (154, 31, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (155, 31, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (156, 32, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (157, 32, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (158, 32, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (159, 32, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (160, 32, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (161, 33, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (162, 33, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (163, 33, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (164, 33, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (165, 33, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (166, 34, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (167, 34, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (168, 34, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (169, 34, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (170, 34, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (171, 35, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (172, 35, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (173, 35, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (174, 35, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (175, 35, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (176, 36, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (177, 36, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (178, 36, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (179, 36, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (180, 36, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (181, 37, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (182, 37, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (183, 37, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (184, 37, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (185, 37, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (186, 38, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (187, 38, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (188, 38, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (189, 38, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (190, 38, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (191, 39, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (192, 39, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (193, 39, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (194, 39, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (195, 39, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (196, 39, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (197, 39, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (198, 39, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (199, 39, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (200, 39, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (201, 41, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (202, 41, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (203, 41, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (204, 41, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (205, 41, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (206, 42, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (207, 42, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (208, 42, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (209, 42, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (210, 42, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (211, 43, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (212, 43, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (213, 43, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (214, 43, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (215, 43, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (216, 44, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (217, 44, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (218, 44, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (219, 44, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (220, 44, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (221, 45, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (222, 45, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (223, 45, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (224, 45, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (225, 45, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (226, 46, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (227, 46, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (228, 46, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (229, 46, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (230, 46, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (231, 47, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (232, 47, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (233, 47, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (234, 47, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (235, 47, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (236, 48, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (237, 48, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (238, 48, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (239, 48, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (240, 48, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (241, 49, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (242, 49, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (243, 49, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (244, 49, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (245, 49, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (246, 49, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (247, 49, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (248, 49, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (249, 49, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (250, 49, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (251, 51, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (252, 51, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (253, 51, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (254, 51, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (255, 51, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (256, 52, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (257, 52, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (258, 52, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (259, 52, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (260, 52, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (261, 53, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (262, 53, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (263, 53, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (264, 53, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (265, 53, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (266, 54, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (267, 54, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (268, 54, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (269, 54, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (270, 54, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (271, 55, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (272, 55, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (273, 55, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (274, 55, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (275, 55, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (276, 56, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (277, 56, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (278, 56, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (279, 56, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (280, 56, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (281, 57, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (282, 57, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (283, 57, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (284, 57, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (285, 57, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (286, 58, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (287, 58, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (288, 58, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (289, 58, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (290, 58, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (291, 59, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (292, 59, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (293, 59, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (294, 59, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (295, 59, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (296, 59, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (297, 59, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (298, 59, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (299, 59, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (300, 59, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (301, 61, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (302, 61, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (303, 61, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (304, 61, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (305, 61, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (306, 62, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (307, 62, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (308, 62, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (309, 62, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (310, 62, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (311, 63, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (312, 63, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (313, 63, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (314, 63, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (315, 63, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (316, 64, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (317, 64, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (318, 64, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (319, 64, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (320, 64, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (321, 65, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (322, 65, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (323, 65, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (324, 65, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (325, 65, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (326, 66, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (327, 66, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (328, 66, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (329, 66, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (330, 66, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (331, 67, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (332, 67, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (333, 67, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (334, 67, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (335, 67, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (336, 68, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (337, 68, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (338, 68, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (339, 68, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (340, 68, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (341, 69, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (342, 69, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (343, 69, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (344, 69, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (345, 69, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (346, 69, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (347, 69, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (348, 69, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (349, 69, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (350, 69, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (351, 71, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (352, 71, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (353, 71, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (354, 71, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (355, 71, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (356, 72, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (357, 72, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (358, 72, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (359, 72, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (360, 72, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (361, 73, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (362, 73, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (363, 73, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (364, 73, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (365, 73, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (366, 74, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (367, 74, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (368, 74, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (369, 74, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (370, 74, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (371, 75, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (372, 75, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (373, 75, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (374, 75, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (375, 75, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (376, 76, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (377, 76, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (378, 76, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (379, 76, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (380, 76, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (381, 77, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (382, 77, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (383, 77, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (384, 77, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (385, 77, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (386, 78, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (387, 78, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (388, 78, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (389, 78, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (390, 78, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (391, 79, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (392, 79, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (393, 79, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (394, 79, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (395, 79, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (396, 79, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (397, 79, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (398, 79, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (399, 79, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (400, 79, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (401, 81, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (402, 81, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (403, 81, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (404, 81, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (405, 81, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (406, 82, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (407, 82, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (408, 82, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (409, 82, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (410, 82, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (411, 83, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (412, 83, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (413, 83, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (414, 83, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (415, 83, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (416, 84, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (417, 84, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (418, 84, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (419, 84, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (420, 84, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (421, 85, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (422, 85, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (423, 85, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (424, 85, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (425, 85, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (426, 86, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (427, 86, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (428, 86, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (429, 86, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (430, 86, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (431, 87, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (432, 87, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (433, 87, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (434, 87, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (435, 87, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (436, 88, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (437, 88, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (438, 88, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (439, 88, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (440, 88, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (441, 89, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (442, 89, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (443, 89, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (444, 89, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (445, 89, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (446, 89, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (447, 89, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (448, 89, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (449, 89, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (450, 89, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (451, 91, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (452, 91, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (453, 91, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (454, 91, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (455, 91, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (456, 92, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (457, 92, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (458, 92, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (459, 92, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (460, 92, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (461, 93, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (462, 93, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (463, 93, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (464, 93, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (465, 93, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (466, 94, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (467, 94, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (468, 94, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (469, 94, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (470, 94, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (471, 95, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (472, 95, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (473, 95, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (474, 95, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (475, 95, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (476, 96, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (477, 96, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (478, 96, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (479, 96, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (480, 96, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (481, 97, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (482, 97, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (483, 97, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (484, 97, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (485, 97, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (486, 98, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (487, 98, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (488, 98, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (489, 98, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (490, 98, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (491, 99, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (492, 99, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (493, 99, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (494, 99, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (495, 99, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (496, 99, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (497, 99, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (498, 99, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (499, 99, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (500, 99, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (501, 101, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (502, 101, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (503, 101, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (504, 101, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (505, 101, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (506, 102, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (507, 102, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (508, 102, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (509, 102, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (510, 102, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (511, 103, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (512, 103, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (513, 103, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (514, 103, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (515, 103, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (516, 104, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (517, 104, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (518, 104, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (519, 104, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (520, 104, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (521, 105, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (522, 105, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (523, 105, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (524, 105, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (525, 105, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (526, 106, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (527, 106, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (528, 106, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (529, 106, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (530, 106, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (531, 107, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (532, 107, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (533, 107, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (534, 107, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (535, 107, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (536, 108, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (537, 108, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (538, 108, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (539, 108, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (540, 108, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (541, 109, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (542, 109, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (543, 109, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (544, 109, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (545, 109, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (546, 109, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (547, 109, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (548, 109, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (549, 109, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (550, 109, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (551, 111, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (552, 111, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (553, 111, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (554, 111, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (555, 111, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (556, 112, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (557, 112, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (558, 112, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (559, 112, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (560, 112, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (561, 113, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (562, 113, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (563, 113, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (564, 113, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (565, 113, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (566, 114, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (567, 114, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (568, 114, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (569, 114, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (570, 114, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (571, 115, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (572, 115, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (573, 115, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (574, 115, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (575, 115, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (576, 116, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (577, 116, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (578, 116, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (579, 116, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (580, 116, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (581, 117, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (582, 117, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (583, 117, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (584, 117, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (585, 117, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (586, 118, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (587, 118, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (588, 118, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (589, 118, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (590, 118, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (591, 119, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (592, 119, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (593, 119, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (594, 119, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (595, 119, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (596, 119, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (597, 119, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (598, 119, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (599, 119, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (600, 119, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (601, 121, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (602, 121, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (603, 121, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (604, 121, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (605, 121, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (606, 122, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (607, 122, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (608, 122, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (609, 122, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (610, 122, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (611, 123, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (612, 123, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (613, 123, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (614, 123, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (615, 123, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (616, 124, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (617, 124, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (618, 124, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (619, 124, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (620, 124, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (621, 125, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (622, 125, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (623, 125, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (624, 125, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (625, 125, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (626, 126, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (627, 126, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (628, 126, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (629, 126, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (630, 126, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (631, 127, 'Disagree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (632, 127, 'Disagree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (633, 127, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (634, 127, 'Agree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (635, 127, 'Agree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (636, 128, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (637, 128, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (638, 128, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (639, 128, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (640, 128, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (641, 129, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (642, 129, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (643, 129, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (644, 129, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (645, 129, 'Agree strongly', 5, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (646, 129, 'Disagree strongly', 1, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (647, 129, 'Disagree a little', 2, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (648, 129, 'Neither agree nor disagree', 3, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (649, 129, 'Agree a little', 4, NULL);
INSERT INTO `inv_option`(`id`, `question_id`, `name`, `grades`, `description`) VALUES (650, 129, 'Agree strongly', 5, NULL);
